[pytest]
testpaths = tests
asyncio_mode = auto
asyncio_default_fixture_loop_scope = session
asyncio_default_test_loop_scope = session
addopts = --maxfail=3 --disable-warnings -q --cov=app --cov-report=term
env =
    AUTH_ENABLED=FALSE
    CURRENT_USER=test
    DATABASE_URL=postgresql+asyncpg://test:test@localhost:5432/base_app_test
    REDIS_URL=
